[project]
name = "xdowm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "bs4>=0.0.2",
    "html2text>=2024.2.26",
    "requests>=2.32.3",
]
